var dish_data, model_select;

function show_base_recipe(ex) {
  dish_data = ex;
  $("#base-recipe-display").removeClass("d-none");
  $("#base-recipe-text").html(dish_data["base"]);
  $("#base-dish").text(dish_data["base-dish"]);
  if (model_select != null){
    $("#target-recipe-display").removeClass("d-none");
    $("#target-recipe-text").html(dish_data["target"][model_select]);
    $("#target-dish").text(dish_data["target-dish"]);
    $("#model-display").text(model_select);
  } else {
    $("#target-recipe-display").addClass("d-none");
  };
};

function show_target_recipe(model) {
  model_select = model;
  if (dish_data != null){
    $("#target-recipe-display").removeClass("d-none");
    $("#target-recipe-text").html(dish_data["target"][model]);
    $("#target-dish").text(dish_data["target-dish"]);
    $("#model-display").text(model);
  };
};

function shape_window() {
  $("body").css("overflow", "hidden");
  console.log($(window).height() - $("#navbar").outerHeight());
  // $("main").css("body", $(window).height());
  let navbar_height = $("#navbar").outerHeight();
  $("#text-display").css("height", $(window).height() - navbar_height);
};

$(document).ready(function() {
  let data = {
    'steam': {
      'base-dish': 'Steamed Turbot', 'target-dish': 'Steamed Hairy Crab', 
      'base': 'Cut 1/3 of the green onion and ginger into fine julienne strips, cut the rest of the green onion into inch pieces, slice the ginger, cut the red pepper into fine julienne strips, and wash the cilantro and set aside.<br> Mix soy sauce, oyster sauce, sugar, a few drops of fish sauce and 4 tablespoons of water, boil in a small pot or microwave for 2 minutes and set aside.<br> Clean the turbot, make diamond-shaped knives on both sides and sprinkle the cooking wine evenly over the fish.<br> And spread the sliced green onion and ginger evenly on the top and bottom of the fish in a suitable size plate.<br> Add to the steamer for 8-9 minutes on high heat, and then turn off the heat.<br> Remove from the heat but do not open the lid and steam for 2 minutes.<br> Remove the onion and ginger from the steamed fish and discard the broth from the plate.<br> Drizzle the cooked soy sauce along the side of the fish, then spread shredded green onion, ginger and red pepper over the fish, and surround the fish with cilantro.<br> Heat 3 tablespoons of vegetable oil in a small pot until it smokes (70 or 80 percent heat) and pour it over the shredded green onion and ginger.', 
      'target': {
        'Human Expert': 'Cut 1/3 of the green onion and ginger into fine julienne strips, cut the rest of the green onion into inch pieces, slice the ginger, cut the red pepper into fine julienne strips, and wash the cilantro and set aside.<br> Mix soy sauce, oyster sauce, sugar, a few drops of fish sauce and 4 tablespoons of water, boil in a small pot or microwave for 2 minutes and set aside.<br> Clean the hairy crab and sprinkle the cooking wine evenly over the hairy crab.<br> And spread the sliced green onion and ginger evenly on the top and bottom of the hairy crab in a suitable size plate.<br> Put into the steamer for 10-15 minutes on high heat and turn off the heat.<br> Remove from the heat but do not open the lid and steam for 2 minutes in vain.<br> Make a dipping sauce with shredded ginger, vinegar, etc.<br> Remove the onion and ginger from the steamer and discard the broth from the plate, and serve the delicious and tempting hairy crabs.', 
        'GPT-2 (D)': 'Wash the crab, put it in a dish, add ginger and green onion, pour in the wine, cover the pot, steam for 15 minutes and sprinkle with chopped cilantro on it!',
        'GPT-2 (D+R)': 'Wash hairy crabs, place in a steamer and steam for 10 minutes.<br> Steam the hairy crabs, remove the gills, remove the crab hearts, crab stomachs, crab intestines, crab gills, crab stomachs, crab intestines, crab intestines, crab intestines, crab intestines, (repeat over and over)',
        'EduCat': 'Cut 1/3 of the green onion and ginger into fine julienne strips, the rest of the green onion and ginger into julienne strips, the dried chili pepper into small pieces, and the cilantro into pieces.<br> Bring soy sauce, oyster sauce, sugar, a few drops of fish sauce and a tablespoon of water to a boil in a small pot.<br> Microwave for 2 minutes.<br> Clean the turbot, make a few cuts on both sides and rub with cooking wine.<br> Put it into a suitable container.<br> Put on the steamer and turn off the heat for 8-9 minutes.<br> After turning off the heat, do not open the lid and simmer for 3 minutes.<br> Remove the ginger from the steamed fish and pour off the steaming broth without it.<br> Pour the cooked sauce along the side of the plate.<br> Spread onion, ginger, chili and cilantro over the fish.<br> Heat a tablespoon of vegetable oil in a pan until it smokes (70 or 80 percent heat).<br> Pour over the shredded green onions and ginger.',
        'Delorean': 'After steaming, lift the crab shell, remove the gills, cut the crab body into two halves and arrange on the plate.<br> Add appropriate amount of oil to the pot.<br> When the oil is hot, add onion, ginger and garlic to burst.<br> Add appropriate amount of steamed fish soy sauce, then add appropriate amount of water.<br> Boil the water and pour it over the crab.<br> Steamed hairy crab is made as follows.<br> Wash the hairy crabs, put them into a steamer, put an appropriate amount of water in the steamer, boil over high heat and then turn the heat to medium and steam for 15 minutes.<br> Steamed hairy crab is made as follows.<br> Wash the hairy crabs, put them into a steamer, put an appropriate amount of water in the steamer, boil over high heat and then turn the heat to medium and steam for 15 minutes.<br> Steamed hairy crab is made as follows.'
      }
    },
    'spicy': {'base-dish': 'Spicy Stir-fried Squid', 'target-dish': 'Spicy Stir-fried Snails', 
      'base': 'The squid must be blanched through water to remove the fishy.<br> Wash the squid neck, remove the middle ink sac and squid mouth, and cut into pieces.<br> Blanch and drain.<br> Heat the oil and then add chili (can be omitted), ginger, garlic into the pot one after another.<br> Stir-fry ingredients until half cooked (I did not add green pepper), add the right amount of salt, add the squid neck.<br> Add cooking wine, soy sauce, LaoGanMa seasoning and cook until tasty.<br> Plate up and eat.', 
      'target': {
        'Human Expert': 'Clean the snails, soak the snails in lightly salted water for 1 hour to spit out the sediment.<br> Boil water in a pot, fish out the soaked snails into the boiling water and blanch them quickly.<br> Fish them out and drain them.<br>  Heat the oil and then add chili (can be omitted), ginger, garlic into the pot one after another.<br> Add green pepper, green garlic and other ingredients and stir-fry them until half cooked, add appropriate amount of salt and add the snails.<br> Add cooking wine, soy sauce, LaoGanMa seasoning and cook until tasty.<br> Plate up and eat.',
        'GPT-2 (D)': '1.<br>Wash the snails with water, put them in a pot with salt and wine, and cook them (about 10 minutes).<br> 2.<br>Drain and set aside.<br> 3.<br>Prepare the side ingredients.<br> 4.<br>Heat the oil and stir fry the ginger and garlic.<br> 5.<br>Pour in the snails and stir-fry them.<br> 6.<br>Then add the bean paste, light soy sauce, dark soy sauce, oyster sauce, sugar, chicken essence, Sichuan pepper, star anise, cinnamon, dried chili pepper and continue to stir-fry.<br> 7.<br>Finally add green and red pepper and stir-fry evenly.<br> 8.<br>Serve it on a plate!',
        'GPT-2 (D+R)': '1. Wash the snails, put them in a pot, add the right amount of water, bring to a boil, remove and drain.<br> 2. Add the oil, add the ginger, garlic, dried chillies and peppercorns, and stir fry.<br> 3. Add the chicken seasoning and stir-fry evenly, then remove it from the pan.<br> 4. Add the right amount of water, bring to the boil, turn down the heat and cook until the soup thickens, add the right amount of chicken seasoning, stir-fry evenly and serve.',
        'EduCat': 'Wash off the sediment in squid, remove the outer skin and guts, cut into circles.<br> Burst large onion (cut into sections) and ginger slices with flavor (I did not add for the sake of good looks).<br> Add the right amount of salt and add snails to fry.<br> Add cooking wine, soy sauce, sugar, oyster sauce, and eat.',
        'Delorean': 'Wash the snail, cut off the tail, soak it in salt water for half an hour, and then rinse it well with water.<br> Pour oil in a pot, add ginger, garlic, dried chili, Sichuan pepper, star anise, cinnamon, and allspice, and stir-fry them.<br> Add the snails and stir-fry.<br> Add wine, light soy sauce, dark soy sauce, oyster sauce, salt, sugar, and beer, cover the pot, boil on high heat, turn to medium heat and cook for 15 minutes.<br> Add the green pepper, absorb the sauce over high heat, and remove from the pot.'
      }
    },
	'kungpao': {'base-dish': 'Kung Pao Chicken', 'target-dish': 'Kung Pao Shrimp Balls', 
      'base': 'Wash and dice the chicken breasts.<br>Add a tablespoon of cooking wine, two tablespoons of soy sauce, a tablespoon of cornstarch, half a tablespoon of oyster sauce and a good amount of black pepper.<br>Mix well and marinate for 10 minutes.<br>Stir-fry the chicken breasts in oil, remove from the oven and keep the oil inside.<br>Add half a spoonful of bean paste and stir-fry for red oil, I didn\'t have bean paste at home so I put in Lao Gan Ma, which is just as delicious.<br>Pour in the stir-fried chicken breasts and diced carrots and cucumbers, when the stir-fry is almost cooked you can taste it and add anything you feel is missing, add some sugar if you want to eat sweet.<br>This is not the sweet version from the restaurant, I think it\'s too sweet and easy to get bored, but this one is very tasty and fragrant.', 
      'target': {
        'Human Expert': 'Wash, peel, devein the shrimps, chopped into mash and marinate in oil, cooking wine, soy sauce and pepper for 15 minutes.<br>Sprinkle with cornstarch and grasp well, stir the shrimp puree filling clockwise, on the strength, grasp the meat puree with the palm of your hand, squeeze out one by one shrimp ball, set aside.<br>Fry peanuts - wash the peanuts in cold water first, soak them for a minute or two, then pour a little oil into a pan, turn on low heat and fry the peanuts, wait until they crackle and sing in the pan.<br>Use the oil left over from frying the peanuts to stir-fry the peppercorns and dried chillies in the pan over a low heat, I also put in some green peppercorns as I like a numbing taste.<br>When the peppers are fragrant, add the onion, garlic and Pixian bean paste and stir-fry to produce red oil.<br>Pour in the shrimp balls and stir-fry, pour in the peanuts and stir-fry.<br>Add the diced green pepper and stir-fry, add soy sauce, vinegar, a little sugar and salt to taste.<br>Serve.',
        'GPT-2 (D)': 'Wash the shrimps, remove the intestines and cut into small pieces;<br> 2. chop the onion and ginger separately and set aside;<br> 3. wash the cucumber and cut into dice;<br> 4. wash the carrot and cut into dice;<br> 5. fry the peanut rice in a pan, let it cool and peel;<br> 6. mix the shrimp and cucumber together, add salt and cooking wine and marinate for about 10 minutes;<br> 7. pour the starch into a bowl, mix in the salt, monosodium glutamate, sugar, vinegar and sesame oil and stir to make a gravy.<br> 8. Put the shrimp, cucumber and carrot on a large plate and serve with the gravy.',
        'GPT-2 (D+R)': 'Wash the shrimps, remove the shrimp threads and marinate for 10 minutes in cooking wine, salt and pepper.<br> Dice the cucumber and chop the onion, ginger and garlic.<br> Heat the oil in a wok and sauté the chopped onion, ginger and garlic.<br> Add the marinated shrimp and stir-fry until browned.<br> Add the diced cucumber and stir-fry well.<br> Add salt, sugar, soy sauce and vinegar and stir-fry well.<br> Sprinkle with chopped spring onion before serving.',
        'EduCat': 'Wash the shrimps, add a spoonful of cooking wine, a spoonful of soy sauce, a spoonful of soy sauce, a spoonful of oyster sauce, a spoonful of white pepper, mix well and marinate for 15 minutes.<br>Don\'t pour off the marinade, fry the red oil in the bean sauce, if there is no bean paste, use Lao Gan Ma is also delicious.<br> Add onion ginger garlic and stir-fry, add chicken breast and cut carrot dice and cucumber dice and stir-fry.<br> When stir-frying, you can taste and add whatever is missing, add some sugar if it is not sweet enough.<br> It\'s not really a very sweet taste, I think it\'s too sweet to be tasty and I eat a lighter one.',
        'Delorean': 'Wash the shrimp, remove the shrimp threads and marinate in cooking wine, salt and pepper for 15 minutes.<br>Dice carrot, cucumber and green pepper.<br>Finely chop the onion, ginger and garlic.<br>Season with sauce: soy sauce, vinegar, sugar, salt, cornstarch and water.<br>Heat the oil in a wok and add the shrimps until browned.<br>Add carrot, cucumber and green pepper and stir-fry until cooked.<br>Add the shrimps, pour in the sauce and stir-fry well, serve.'
      }
    },
	'cold': {'base-dish': 'Cold Tofu', 'target-dish': 'Cold Tofu with Century Egg', 
      'base': 'Cut the tofu into cubes and blanch the shredded carrot, pepper and tofu cubes in boiling water.<br>Strain, chop the coriander and scatter it over the top, add the minced garlic and ginger, drizzle with soy sauce, balsamic vinegar, sesame oil and spicy sauce.<br>Heat two tablespoons of pepper oil, turn off the heat, add a little sugar and heat through the remaining heat, drizzle over the vegetables.<br>Mix well and serve.', 
      'target': {
        'Human Expert': 'Peel the skin of the century egg and cut into quarters; cut the tofu into cubes, shred the carrot, julienne the pepper and cut the coriander.<br>Blanch the tofu cubes and carrots in boiling water.<br>Arrange the century eggs, tofu, carrot, pepper and coriander in order, add garlic and ginger, drizzle with soy sauce, vinegar, sesame oil and spicy sauce.<br>Heat two tablespoons of pepper oil, turn off the heat, add a little sugar and heat through the remaining heat, drizzle over the vegetables.<br>Mix well and serve.',
        'GPT-2 (D)': 'Prepare all the ingredients, cut the century egg into cubes, wash and cut the coriander;<br> cook the tofu in a pan, drain and serve;<br> pour the egg, chilli sauce and soy sauce together and stir to make a sauce;<br> drizzle with the sauce and enjoy!',
        'GPT-2 (D+R)': 'Cut the century egg into cubes, shred the carrot, chop the coriander, mince the garlic and cut the chillies into rings, add to a bowl, add the soy sauce, vinegar, salt, sugar, sesame oil and chilli oil and mix well.<br> Pour the dressing over the tofu and mix well.',
        'EduCat': 'Cut tofu into cubes, put shredded carrot, shredded sharp pepper, and tofu cubes on a plate, and mince the coriander, garlic, and onion.<br> Start a pot and boil a spoonful of pepper oil with soy sauce, vinegar, sesame oil, salt, and sugar.<br> Turn off the heat and put in a little sugar, heat the remaining heat and pour into a plate.<br> Mix well.',
        'Delorean': 'Cut the century egg into small pieces, cut the tofu into cubes, mince the garlic, cut the chilli into rings and cut the coriander into pieces and add to a bowl.<br>Seasoning: soy sauce, vinegar, sugar, salt, sesame oil, chilli oil, pepper oil, chilli oil, pepper powder, minced garlic, chilli, coriander, mix well.<br>Cold tofu with century egg is prepared as follows.<br>Cut the tofu into cubes, cut the century egg into cubes, chop the spring onion, cut the chilli into rings and cut the coriander into pieces and place in a bowl.'
      }
    },
	'smother': {'base-dish': 'Smothered Chicken', 'target-dish': 'Smothered Chicken with Abalone', 
      'base': 'Marinate the processed chicken with ginger, spring onions and seasoning for 2 hours, also marinate the chicken belly with ginger, spring onions and seasoning inside.<br>Line the bottom of the pressure cooker with a layer of sliced ginger and spring onions.<br>Add the marinated chicken and pour in the marinade.<br>Cover the pan with a lid, place the pressure relief valve, turn on the heat to medium and cook until the pressure relief valve swings considerably, then reduce the heat to low and cook for another 10 minutes, then turn off the heat.<br>When the pressure indicator drops, open the lid and the smothered chicken is ready.<br>Serve on a plate, top with stock and enjoy.', 
      'target': {
        'Human Expert': 'Marinate the processed chicken with ginger, spring onion and seasoning for 2 hours, also marinate the chicken belly with ginger, spring onion and seasoning inside; gut the abalone, rinse and set aside.<br>Spread a layer of ginger and spring onions in the bottom of the pressure cooker.<br>Add the marinated chicken and pour in the marinade.<br>Cover the pan with a lid, place the pressure relief valve, turn on the heat to medium and cook until the pressure relief valve swings considerably, then reduce the heat to low and cook for another 10 minutes.<br>When the pressure indicator drops, open the lid, add the abalone, turn on the heat again and stir-fry for 2-3 minutes, then turn off the heat.<br>Serve on a plate, top with stock and enjoy.',
        'GPT-2 (D)': 'Prepare the ingredients, wash and cut the chicken, slice the ginger and garlic, cut the green onion and heat the oil in a pot;<br> add the ginger and garlic and stir-fry until browned, add the wine and soy sauce and continue to stir-fry evenly, add the right amount of water and bring to a boil;<br> turn down the heat and simmer for about 20 minutes, add the red dates and simmer for another 5-10 minutes, finally sprinkle the green onions and you\'re ready to go!',
        'GPT-2 (D+R)': 'Wash the chicken, cut into pieces, add the wine, soy sauce, soy sauce, oyster sauce, salt, sugar, cornstarch and marinate well for half an hour.<br> Heat the oil in a wok, add the ginger, garlic cloves, star anise, cinnamon, sesame leaves and dried chillies and stir fry.<br> Add the chicken and stir-fry until browned.<br> Add a can of beer and add a good amount of water to cover the chicken.<br> Bring to the boil over high heat, reduce the heat and simmer for 20 minutes.<br> Add the potatoes, carrots and onions and continue to simmer for 10 minutes.<br> Add the peppers and reduce the sauce over high heat.<br> Remove from the pan and sprinkle with chopped spring onion.',
        'EduCat': 'Marinate the chicken with the ginger, spring onions and seasoning for half an hour, also add the ginger, spring onions and seasoning to the belly of the chicken.<br>Line the bottom of the pressure cooker with a layer of sliced ginger and spring onions, place the marinated chicken and pour in the marinade.<br>Cover with a lid and cook on high heat for 10 minutes, open the lid substantially and cook on low heat for 10 minutes.<br>Turn off the heat and open the lid when the temperature is high and the pressure has dropped.<br>Remove from the pan and drizzle with the stock and serve.',
        'Delorean': 'Wash the chicken, cut into pieces and marinate for half an hour in cooking wine, soy sauce, soy sauce, oyster sauce, salt, sugar, cornstarch and ginger.<br>Wash the abalone and cut into fancy cuts.<br>Cut the spring onion into pieces, slice the ginger and slice the garlic.<br>Heat the oil in a pan, add the onion, ginger and garlic, stir-fry the chicken until browned.<br>Add the abalone and stir-fry.<br>Add the soy sauce, soy sauce, oyster sauce, salt, sugar and cooking wine and stir-fry well.<br>Add an appropriate amount of water to cover the chicken pieces, bring to the boil over high heat, reduce the heat and simmer for 20 minutes.'
      }
	}
  }
  shape_window();
  $("input[name=dish_filter]").click(function() { show_base_recipe(data[$("input[name=dish_filter]:checked").val()]) });
  $("input[name=model_filter]").click(function() { show_target_recipe($("input[name=model_filter]:checked").val()) });
});

